

collections_config:
  people:
    _inputs:
      avatar:
        type: image
      excerpt:
        type: textarea
        comment: Short description of affiliation and activity
      portfolio_item_category:
        type: array
        options:
          values: people
        instance_value: people
      portfolio_item_tag:
        label: Status and Affiliation
        options:
          values:
            - former member
            - current member
            - Mpala
            - Princeton
            - USCB
            - graduate student
            - undergraduate student
            - research intern
            - thesis advisee
            - high school student
            - postdoc
            - lab visitor
            - research staff
  publications:
    _inputs:
      portfolio_item_category:
        instance_value: publications


_inputs:
  author:
    type: select
    options:
      values: data.authors
  portfolio_item_category:
    hidden: true
    type: choice
  date:
    type: date
    instance_value: NOW
  id: 
    instance_value: UUID
    hidden: true
  portfolio_item_tag:
    type: multichoice
    allow_empty: false
    
    
  

