

collections_config:
  people:
    icon: people
    
    _inputs:
      avatar:
        type: image
        uploads: assets/[collection]/{title|slugify}
      excerpt:
        type: textarea
        comment: Short description of affiliation and activity
      portfolio-item-category:
        options:
          values:
            - people
      portfolio-item-tag:
        label: Status and Affiliation
        options:
          values:
            - former member
            - current member
            - Mpala
            - Princeton
            - USCB
            - graduate student
            - undergraduate student
            - research intern
            - thesis advisee
            - high school student
            - postdoc
            - lab visitor
            - research staff
  publications:
    _inputs:
      portfolio-item-category:
        options:
          values:
            - publications


_inputs:
  author:
    type: select
    options:
      values: data.authors
  portfolio-item-category:
    hidden: true
    allow_empty: false
    type: select
  date:
    type: date
    instance_value: NOW
  id: 
    instance_value: UUID
    hidden: true
  portfolio-item-tag:
    type: multiselect
    allow_empty: false
    
    
  

